<div class="container">
    JTL Test Plugin Page! {$jtl_test_var}

    <div class="jtl_test_test_cases">
        <p>This text is generated by the Plugin "JTL Test". It is for demonstration purposes only.'</p>
        <p>Uninstall it if you do not want to see this output.</p>

        <div class="jtl_test_stuff" id="foo">
            <p class="test">Gelber Hintergrund</p>
        </div>
        <div class="jtl_test_stuff" id="bar">
            <p class="test">Blauer Hintergrund</p>
        </div>
        <div class="jtl_test_stuff" id="defined-color" style="background:{$exampleConfigVars->getValue('jtl_color_1')};">
            <p class="test">Benutzerdefinierte Hintergrundfarbe</p>
        </div>
    </div>
</div>
