#!/usr/bin/env php
<?php declare(strict_types=1);

use JTL\Console\Application;
use JTL\Shop;

if (PHP_SAPI !== 'cli') {
    echo 'Error: Shop CLI should be invoked via the CLI version of PHP, not the ' . PHP_SAPI . ' SAPI' . PHP_EOL;
    exit;
}

set_error_handler(static function($code, $description, $file = null, $line = null, $context = null) {
    if ($code === E_ERROR) {
        echo 'Error (' . $code . '): ' . $description . ' in [' . $file . ', line ' . $line . ']' . PHP_EOL;
        exit;
    }
});

const CLI_BATCHRUN = true;
const PFAD_INCLUDES = 'includes/';

if (file_exists(__DIR__ . '/' . PFAD_INCLUDES . 'config.JTL-Shop.ini.php')) {
    require_once __DIR__ . '/' . PFAD_INCLUDES . 'config.JTL-Shop.ini.php';
}
if (!defined('PFAD_ROOT')) {
    define('PFAD_ROOT', __DIR__ . '/');
}


require_once PFAD_ROOT . PFAD_INCLUDES . 'defines.php';
require_once PFAD_ROOT . PFAD_INCLUDES . 'autoload.php';
Shop::setLanguage(1, 'ger');
$application = new Application();
$application->initPluginCommands();
$application->run();
